version: '3.9'

services:
  db:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - userservice:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: userService
    ports:
    - "8080:8080"
    environment:
      DB_CONT_NAME: db
      DB_PORT: 5432
      DB_DATABASE: postgres
#      paste the api key below
      API_KEY: b95e8400-c114-11ee-a2d4-5d9094216cbb
    depends_on:
      - db
    restart: always

volumes:
  userservice: